### ISSUE TITLE
__init__ missing argument created

### ISSUE THREAD

**Issue by shruthi-raghuraman** [thoth-station/notebooks#44]
**Describe the bug** 
When creating the dataframe in the setup, JSON file has created field not in the __init__ attributes. When the created attribute is added, other type errors show up when going through the document.

**To Reproduce** 
1. Run the file and when running the setup. Error occurs because JSON file has field created that isn't present in the attributes. 

**Expected behaviour** 
JSON shouldn't have any unexpected fields. 

**Screenshots** 

**First error:**

TypeError                                 Traceback (most recent call last)
<ipython-input-14-404e95f3b4f0> in <module>
     15 #     print(document)
     16     document.pop('created', None)
---> 17     inspection_results.append(InspectionResult(**document))

TypeError: __init__() missing 1 required positional argument: 'created'

Error after created was added: 
Type errors in specification: InspectionSpecification and status: InspectionStatus

**Additional context**
@harshad16  helped changing the type for version and adding index i. This could fix the issue. Code was changed in Requirements and RequirementsLocked in the __post_init__(self) functions for self.packages and self.default:

self.packages = [
                Package(**dict(name=p, version=v, index=i)) for i,(p, v) in enumerate(self.packages.items())
            ]

self.dev_packages = [
                Package(**dict(name=p, version=v)) for p, v in self.dev_packages.items()
            ]

**Comment by shruthi-raghuraman** [comment]
@pacospace here's the link to the code https://github.com/thoth-station/notebooks/blob/master/notebooks/development/Experiments%20with%20inspection%20jobs.ipynb

**Comment by CermakM** [comment]
Hey @shruthi-raghuraman, I think that the schema of inspection run has slightly changed since this notebook was written. It is possible that  there are some missing / unexpected attributes in the JSON file. We're currently working on processing those inspection JSONs (see https://docs.google.com/document/d/1O66cjNj_rGJdC7Wx2HcskgjrHawdo9fWuy8tpTkNpaQ/edit and https://trello.com/c/7IiBLufs/560-grouping-of-inspection-job-results-based-on-given-criteria-nokr) so I suggest not spending too more time than necessary by fixing this one.

**Comment by shruthi-raghuraman** [comment]
@CermakM That's what I thought too! Once those attributes were fixed I got a few graphs working but columns that were graphed had different array sizes/names. I  am just read through the code to understand the graphs and see the displays on the github page. Thanks for letting me know!

**Comment by shruthi-raghuraman** [comment]
@CermakM Once those attributes were fixed I got a few graphs working but columns that were graphed had different array sizes/names. I am just reading through the code to understand the graphs and see the displays on the github page. Thanks for letting me know!

**Comment by CermakM** [comment]
@shruthi-raghuraman can you create a new PR with the fix you came up with so that nobody who happens to fire up this notebook afterwards runs into the issue again?

**Comment by goern** [comment]
is this still valid?

**Comment by shruthi-raghuraman** [comment]
@goern At the time this notebook was created I believe the schema was different. Since then new attributes were added. I believe the first fixes made some sense but I wasn't able to completely refactor this notebook for the new schema. All functions in thoth lab however added from the summer project, however, was updated to utilize the new schema.
